export const ON_OPEN_MODAL = 'ON_OPEN_MODAL';
export const ON_CLOSE_MODAL = 'ON_CLOSE_MODAL';

export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';
export const FETCH_PHONES_INCREASE = 'FETCH_PHONES_INCREASE';

export const FETCH_ALL_PHONES_START = 'FETCH_ALL_PHONES_START';
export const FETCH_ALL_PHONES_SUCCESS = 'FETCH_ALL_PHONES_SUCCESS';
export const FETCH_ALL_PHONES_FAIL = 'FETCH_ALL_PHONES_FAIL';

export const CHANGING_SETTINGS_STATE = 'CHANGING_SETTINGS_STATE';